name: Your New Jekyll Site
markdown: kramdown
#highlighter: pygments
#paginate: 5
#paginate_path: "/blog/:num"
#languages: ["en"]
destination: "./public"
exclude: ["Gemfile", "Gemfile.lock"]
keep_files: []
