version: '3'
services:

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=smartvpn_production

  redis:
    image: redis

  app:
    image: mexx/smartvpn-billing:latest
    ports:
      - "80:3000"
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=production
      - PGHOST=postgres
      - REDIS_URL=redis://redis:6379
      - DEFAULT_HOST
      - EMAIL_USER
      - EMAIL_PASS
      - EMAIL_FROM
      - SECRET_TOKEN
    depends_on:
      - postgres
      - redis
    command: >
      /bin/bash -c "
        while ! nc -z postgres 5432;
        do
          echo Waiting for PG;
          sleep 1;
        done;
        rake db:migrate;
        rm -f /app/tmp/pids/server.pid;
        foreman start;
      "

  node:
    image: mexx/smartvpn-node:latest
    ports:
      - "443:443/udp"
    environment:
      - SECRET_TOKEN
      - API_HOST=app:3000
      - HOSTNAME
    cap_add:
      - NET_ADMIN
    depends_on:
      - app
    volumes:
      - type: volume
        source: pki
        target: /hooks/pki/keys
        volume:
          nocopy: true
    command: >
      /bin/bash -c "
        while ! nc -z app 3000;
        do
          echo Waiting for Billing;
          sleep 1;
        done;
        /hooks/entrypoint.sh;
      "
volumes:
  pki:
