# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  script = <<SCRIPT
    sudo apt-get -qqy update
    sudo apt-get -qqy install docker.io docker-compose
    sudo su vagrant
    sudo usermod -aG docker vagrant
SCRIPT

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision :shell, inline: script
end
