version: '3'
services:

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=smartvpn_production

  redis:
    image: redis

  app:
    image: mexx/smartvpn-billing
    ports:
      - "80:3000"
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=production
      - PGHOST=postgres
      - REDIS_URL=redis://redis:6379
      - SECRET_TOKEN
    depends_on:
      - postgres
      - redis
    command: >
      /bin/bash -c "
        while ! nc -z postgres 5432;
        do
          echo Waiting for PG;
          sleep 1;
        done;
        rake db:migrate;
        rm -f /app/tmp/pids/server.pid;
        foreman start;
      "
