# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  script = <<SCRIPT
    sudo apt-get -qqy update
    sudo apt-get -qqy install docker.io docker-compose
SCRIPT

  config.vm.provision :shell, inline: script
end
